### ISSUE TITLE
Skip dirs not working

### ISSUE THREAD

**Issue by bitcreator** [roistat/docker-golangci-lint#1]
I have two dirs which I want to skip. I added file .golangci.yml in project root. But lint scanned this dirs.
```
run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true
  # next dirs are always skipped: vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - mocks
    - version
  skip-files:

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus

linters:
  enable-all: true
  disable:
    - maligned
```
